CREATE TABLE TP_DEPARTAMENTOS (
    ID							INT NOT NULL IDENTITY(1,1),
    DESCRIPCION                 TEXT,
    FECHA_CREATE                DATE
	CONSTRAINT PK_DEPARTAMENTOS UNIQUE (ID)
);


INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('AMAZONAS', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('ANTIOQUIA', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('ARAUCA', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('ATLÁNTICO', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('BOLÍVAR', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('BOYACÁ', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('CALDAS', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('CAQUETÁ', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('CASANARE', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('CAUCA', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('CESAR', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('CHOCÓ', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('CÓRDOBA', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('CUNDINAMARCA', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('GUAINÍA', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('GUAVIARE', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('HUILA', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('LA GUAJIRA', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('MAGDALENA', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('META', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('NARIÑO', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('NORTE DE SANTANDER', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('PUTUMAYO', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('QUINDÍO', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('RISARALDA', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('SAN ANDRÉS Y PROVIDENCIA', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('SANTANDER', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('SUCRE', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('TOLIMA', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('VALLE DEL CAUCA', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('VAUPÉS', GETDATE());
INSERT INTO TP_DEPARTAMENTOS (DESCRIPCION, FECHA_CREATE) VALUES ('VICHADA', GETDATE());
