CREATE TABLE TP_SEXOS (
    ID							INT NOT NULL IDENTITY(1,1),
    DESCRIPCION                 TEXT,
    FECHA_CREATE                DATE
	CONSTRAINT PK_SEXOS UNIQUE (ID)
);

INSERT INTO TP_SEXOS (DESCRIPCION, FECHA_CREATE) VALUES 
('MASCULINO', GETDATE()),
('FEMENINO', GETDATE()),
('NO BINARIO', GETDATE()),
('OTRO', GETDATE());
